
export const AUTH_ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', 
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  LOGOUT: 'LOGOUT'
};

export const MODEL_ACTION_TYPES = {
  ADD_MODEL_REQUEST: 'ADD_MODEL_REQUEST',
  ADD_MODEL_SUCCESS: 'ADD_MODEL_SUCCESS',
  ADD_MODEL_FAILURE: 'ADD_MODEL_FAILURE',
  FETCH_MODELS_REQUEST: 'FETCH_MODELS_REQUEST',
  FETCH_MODELS_SUCCESS: 'FETCH_MODELS_SUCCESS', 
  FETCH_MODELS_FAILURE: 'FETCH_MODELS_FAILURE',
  DELETE_MODEL: 'DELETE_MODEL'
};

export const DESIGN_ACTION_TYPES = {
  CREATE_DESIGN_REQUEST: 'CREATE_DESIGN_REQUEST',
  CREATE_DESIGN_SUCCESS: 'CREATE_DESIGN_SUCCESS',
  CREATE_DESIGN_FAILURE: 'CREATE_DESIGN_FAILURE',
  SAVE_DESIGN: 'SAVE_DESIGN',
  UPDATE_DESIGN: 'UPDATE_DESIGN', 
  DELETE_DESIGN: 'DELETE_DESIGN',
  FETCH_DESIGNS_REQUEST: 'FETCH_DESIGNS_REQUEST',
  FETCH_DESIGNS_SUCCESS: 'FETCH_DESIGNS_SUCCESS',
  FETCH_DESIGNS_FAILURE: 'FETCH_DESIGNS_FAILURE',
  SET_CURRENT_DESIGN: 'SET_CURRENT_DESIGN'
};

export const USER_ACTION_TYPES = {
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER'
};